# 公共配置文件
# @author stephen qiu
spring:
  application:
    name: mallchat-backend
  # 默认 dev 环境
  config:
    activate:
      on-profile: default
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # 缓存
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s
  # session 配置
  session:
    # 开启分布式 session（须先配置 Redis）
    store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  datasource:
    driver-class-name: ${dev.mysql.datasource.driver-class-name}
    url: ${dev.mysql.datasource.url}
    username: ${dev.mysql.datasource.username}
    password: ${dev.mysql.datasource.password}
  # Redis 配置
  # todo 需替换配置，然后取消注释
  redis:
    enabled: true
    database: ${dev.redis.database}
    host: ${dev.redis.host}
    port: ${dev.redis.port}
    timeout: ${dev.redis.timeout}
  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
  elasticsearch:
    uris: ${dev.elasticsearch.uris}
  # 邮件配置
  mail:
    # todo 是否开启邮件功能
    enable: false
    # 邮件服务器配置
    host: smtp.163.com
    # 端口号
    port: 25
    # 发送邮件的邮箱地址
    username: xxxxxxxx@163.com
    # 发送邮件的邮箱验证密码或者授权码
    password: xxxxxxxx
    # 邮件默认编码
    default-encoding: UTF-8
    # 邮箱通讯协议
    protocol: smtp
  # RabbitMQ配置
  rabbitmq:
    # todo 是否开启RabbitMQ（预先关闭）
    enable: false
    host: ${dev.rabbitmq.host}
    port: ${dev.rabbitmq.port}
    username: ${dev.rabbitmq.username}
    password: ${dev.rabbitmq.password}
    max-await-timeout: 3000
    # 虚拟主机
    virtual-host: /
    # 消息确认（ACK）
    publisher-confirm-type: correlated #确认消息已发送到交换机(Exchange)
    publisher-returns: true #确认消息已发送到队列(Queue)
    template:
      mandatory: true
    # 是否手动ACK
    listener:
      type: simple
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB


############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # todo 是否启用SaToken认证鉴权功能（此处为false并不是禁用SaToken，而是让SaToken相关注解失效，预先开启）
  enable-sa: true
  # todo 是否使用JWT格式的Token（建议如果没有开启redis配置就不要开启JWT格式的Token，预先关闭）
  enable-jwt: true
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  # token前缀  注意必须是 Bearer {token}, Bearer后面加空格
  token-prefix: Bearer
  # jwt秘钥
  jwt-secret-key: ${dev.sa-token.jwt-secret-key}

# 日志配置
server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
# MyBatis Plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 微信相关
wx:
  enabled: true
  # 微信公众平台
  # todo 需替换配置
  mp:
    token: xxx
    aesKey: xxx
    appId: xxx
    secret: xxx
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory
  # 微信开放平台
  # todo 需替换配置
  open:
    appId: xxx
    appSecret: xxx

# 腾讯云COS对象存储配置
# todo 是否开启
cos:
  client:
    enable: true
    accessKey: ${dev.cos.client.accessKey}
    secretKey: ${dev.cos.client.secretKey}
    region: ${dev.cos.client.region}
    bucket: ${dev.cos.client.bucket}

# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    description: "StephenQiu的接口文档信息。"
    concat: "Stephen Qiu"
    email: "popcornqhd@gmail.com"
    url: "https://github.com/Stephenqhd30"
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.stephen.popcorn.controller
          - com.stephen.popcorn.elasticsearch.controller

# Redisson 配置
redisson:
  enabled: false
  database: ${dev.redisson.database}
  host: ${dev.redisson.host}
  port: ${dev.redisson.port}
# 对象存储配置
oss:
  # MinIO OSS配置
  minio:
    # todo 是否开启
    enable: false
    # 域名（格式：【ip:port】）
    endpoint: 127.0.0.1:9000
    # 是否开启TLS
    enable-tls: false
    # 用户的 SecretId
    secret-id: xxxxxxxx
    # 用户的 SecretKey
    secret-key: xxxxxxxx
    # 桶名称
    bucket-name: xxxxxxxx
  # 阿里云OSS配置
  ali:
    # todo 是否开启
    enable: false
    # 域名 以华东1（杭州）为例，Endpoint填写为https://oss-cn-hangzhou.aliyuncs.com。
    endpoint: https://oss-xx-xxx.aliyuncs.com
    # 用户的 SecretId
    secret-id: xxxxxxxx
    # 用户的 SecretKey
    secret-key: xxxxxxxx
    # 桶名称
    bucket-name: xxxxxxxx
# 讯飞星火api
xunfei:
  # todo 是否开启星火API功能
  enabled: false
  client:
    appid: ${dev.xunfei.client.appid}
    api-key: ${dev.xunfei.client.api-key}
    api-secret: ${dev.xunfei.client.api-secret}

# WebSocket配置
websocket:
  # todo 是否开启（预先关闭）
  enable: false
  # websocket服务端口
  port: 39999
  # BOSS线程组线程数
  boss-thread: 4
  # WORKER线程组线程数
  worker-thread: 16

